### ISSUE TITLE
A problem with iframes and need the link 'donotnegotiate'

### ISSUE THREAD

**Issue by erikaris** [webrecorder/webrecorder#300]
Hi, 
I am currently working on a project about calculating the damage on a memento (https://github.com/erikaris/web-memento-damage). The calculation is done by measuring the impact of the missing resources on the memento’s representation. 
I test my tool using this URI: https://webrecorder.io/shawnmjones/scholarly-tool-archivability-nautilus-3-sentence-science/20161219213326/http://nautil.us/search/ANKUR%20PALIWAL. But it returns some errors because it cannot access the resources (images, css, etc) inside the iframe. I also found that the iframe and the parent do not have the same origin so that they cannot communicate with each other. 
Is there any way to get the “raw” presentation of the webrecorder’s memento? So, I can get the original web presentation without any resources from webrecorder? Maybe like adding “id_” on memento from web.archive.org?
I also do not find the special-purpose link “donotnegotiate” in the HTTP Link header when I sent the “GET/HEAD” request, or at least that’s what I found when I curl the resource’s URI. This link is needed to identify the resources that are excluded from datetime negotiation as described in https://tools.ietf.org/html/rfc7089#section-4.5.8. 
Could you also please provide the link value ‘donotnegotiate’ for the header? 
Thanks.

**Comment by ikreymer** [comment]
Hi,
Webrecorder supports the same `id_` interface as you're familiar with.
However, webrecorder.io is configured to serve archived content from different domain (wbrc.io) than the application itself is running on. This is needed for a variety of security and usability reasons (cookies, cross-domain js access). To make this work, the session cookie from webrecorder.io is passed to wbrc.io via redirect, so that slightly complicates your use case of memento damage analysis. But once you have the cookie, you should be able to access the `id_` path

I think what you can do is:
1) Request to: `https://wbrc.io/shawnmjones/scholarly-tool-archivability-nautilus-3-sentence-science/20161219213326id_/http://nautil.us/search/ANKUR%20PALIWAL`

2) This will send you a redirect to a special url that will return a session cookie, `Set-Cookie: __wr_sesh: <value>` and redirect back to `https://wbrc.io/shawnmjones/scholarly-tool-archivability-nautilus-3-sentence-science/20161219213326id_/http://nautil.us/search/ANKUR%20PALIWAL`

3) Now you can make requests to `https://wbrc.io/...` as long as you include your session cookie.

I'm not sure the 'donotnegotiate' header is needed here, as using the `id_` path retrieves the original, unrewritten resources only.
This is assuming that you are looking at the unrewritten resources?

If you are looking at the rewritten page, then you're right, a browser won't let you do cross-frame access from the top frame. You should then inject your analysis script into the content `<iframe>` 

I haven't had a chance to take a closer look, but overall, the damage analysis seems like a really great idea! Let us know if there's other things we can do to help your use case.

**Comment by erikaris** [comment]
Hi, 

I don't really understand what you mean with " as long as you include your session cookie"?  Can I just replace "https://wbrc.io/shawnmjones/scholarly-tool-archivability-nautilus-3-sentence-science/20161219213326id_/http://nautil.us/search/ANKUR%20PALIWAL" with "https://wbrc.io/shawnmjones/scholarly-tool-archivability-nautilus-3-sentence-science/20161219213326id_/http://nautil.us/search/ANKUR%20PALIWAL"?

**Comment by ikreymer** [comment]
We've simplified things a bit, and publicly available content no longer requires cookies, eg:
https://content.webrecorder.io/shawnmjones/scholarly-tool-archivability-nautilus-3-sentence-science/20161219213326id_/http://nautil.us/search/ANKUR%20PALIWAL
should just be accessible (domain is now content.webrecorder.io)
