### ISSUE TITLE
Consider IPFS integration

### ISSUE THREAD

**Issue by kumavis** [webrecorder/webrecorder#33]
IPFS is an open-source protocol for content-addressable storage.

https://www.youtube.com/watch?v=skMTdSEaCtA

Utilitarian reasons to use IPFS:
* massive storage savings: all repeated assets are stored once ( e.g. repeated exact version of jquery or an image )
* massive bandwidth savings: the community you serve can safely and reliably distribute the assets on your behalf

**Comment by ikreymer** [comment]
Already being considered :) See: ipfs/archives#28 and ipfs/apps#3
Current issue is to figure out best way to store WARC records into IPFS, since Webrecorder saves HTTP traffic, including HTTP headers, not just files, and is the standard format in web archiving.

I made an experimental add-on to pywb library that writes WARCs to IPFS: https://github.com/ikreymer/pywb-ipfs

Not sure this is the best way yet, though.
Once we have WARC in IPFS figured out, this will be much easier.

There are also privacy issues, some users may want to keep things private, and/or have option to delete pages, and will probably want a different storage backend for that.

**Comment by kumavis** [comment]
fantastic! I'll close this
