### ISSUE TITLE
Add a simple internal blog where we can post feature updates

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#6]
Very simple blog to post updates about the beta. Probably just write posts in markdown.
Maybe can integrate https://github.com/getpelican/ or may be simple enough that don't even need it..

**Comment by ibnesayeed** [comment]
If the updates are tied with the releases then all the relevant notes can go in the release description. [Docker Compose](https://github.com/docker/compose/releases) uses this technique. Otherwise simply create a [GitHub Pages](https://pages.github.com/) powered [web site for the project](http://webrecorder.github.io/). GitHub uses Jekyll that [can be used for blogging](https://help.github.com/articles/using-jekyll-with-pages/).

**Comment by m4rk3r** [comment]
http://blog.webrecorder.io/ !!
