### ISSUE TITLE
twitter does not open correctly

### ISSUE THREAD

**Issue by Feribv** [webrecorder/webrecorder#786]
if you try to open a twitter account under the webrecorder.io it will not load correctly and you cannot scroll in it.
Thanks for trying to solve this issue!

**Comment by m4rk3r** [comment]
Hi @Feribv, I believe you are seeing twitter rate limiting webrecorder. Recording twitter via webrecorder.io can cause rate limiting issues since the requests are all coming from a limited range of IPs. [The Webrecorder Desktop App](https://github.com/webrecorder/webrecorder-desktop) should help get around this issue, by using your local IP. You can then upload your recordings to the hosted service.
